from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path

from .launcher_builder import build_patchops_bundle_launcher


@dataclass(frozen=True)
class BundleAuthoringResult:
    bundle_root: Path
    manifest_path: Path
    bundle_meta_path: Path
    readme_path: Path
    launcher_path: Path
    content_root: Path


def create_starter_bundle(
    bundle_root: str | Path,
    *,
    patch_name: str,
    target_project: str,
    target_project_root: str,
    wrapper_project_root: str = r"C:\dev\patchops",
    recommended_profile: str = "generic_python",
    mode: str = "apply",
) -> BundleAuthoringResult:
    root = Path(bundle_root).resolve()
    root.mkdir(parents=True, exist_ok=True)

    content_root = root / "content"
    content_root.mkdir(parents=True, exist_ok=True)

    manifest_path = root / "manifest.json"
    bundle_meta_path = root / "bundle_meta.json"
    readme_path = root / "README.txt"
    launcher_path = root / "run_with_patchops.ps1"

    manifest = {
        "manifest_version": "1",
        "patch_name": patch_name,
        "active_profile": recommended_profile,
        "target_project_root": target_project_root,
        "backup_files": [],
        "files_to_write": [],
        "validation_commands": [],
        "smoke_commands": [],
        "audit_commands": [],
        "cleanup_commands": [],
        "archive_commands": [],
        "failure_policy": {},
        "report_preferences": {
            "report_dir": None,
            "report_name_prefix": patch_name,
            "write_to_desktop": True,
        },
        "tags": [
            "bundle",
            "starter",
            "python_owned_authoring",
        ],
        "notes": "Starter bundle generated by PatchOps Python bundle authoring helper.",
    }

    bundle_meta = {
        "bundle_schema_version": 1,
        "patch_name": patch_name,
        "target_project": target_project,
        "recommended_profile": recommended_profile,
        "target_project_root": target_project_root,
        "wrapper_project_root": wrapper_project_root,
        "content_root": "content",
        "manifest_path": "manifest.json",
        "launcher_path": "run_with_patchops.ps1",
    }

    readme = f"""PatchOps starter bundle
======================

Patch name : {patch_name}
Target     : {target_project}
Profile    : {recommended_profile}

This starter bundle was generated by the Python bundle authoring helper.

Bundle root files
- manifest.json
- bundle_meta.json
- README.txt
- run_with_patchops.ps1
- content/

Next steps
1. Put staged target files under content/ using target-relative paths.
2. Fill manifest.json files_to_write and validation_commands.
3. Review the root launcher.
4. Package the bundle root contents directly.
"""

    launcher_text = build_patchops_bundle_launcher(
        wrapper_project_root=wrapper_project_root,
        mode=mode,
        launcher_directory_relative_to_bundle_root=False,
    )

    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    bundle_meta_path.write_text(json.dumps(bundle_meta, indent=2) + "\n", encoding="utf-8")
    readme_path.write_text(readme, encoding="utf-8")
    launcher_path.write_text(launcher_text, encoding="utf-8")

    return BundleAuthoringResult(
        bundle_root=root,
        manifest_path=manifest_path,
        bundle_meta_path=bundle_meta_path,
        readme_path=readme_path,
        launcher_path=launcher_path,
        content_root=content_root,
    )
